### ISSUE TITLE
Repo cleaning

### ISSUE THREAD

**Issue by Vuurvos1** [riek-lt/Riek-pointbot#2]
List of things to look at:
- **Fun textswapper** is depricated and uses jQuery 🤮 
- **textswapfiles** might also be depricated if **Fun textswapper** also is depricated
   - clean up `.gitignore` if so
- Some folders contain both a readme.txt and a `readme.md`, 
   I would recommend converting everything to md
- Generate a real license file, 
  this can be done under `Add file` > `Create new file` > and naming the file `LICENSE`
- No `index.html` found in **try-it-yourself**
- `twitchTTS-feature-serverProxy/index.js` and `twitchTTS-feature-serverProxy/abc/index.js` 
  look to be the same
- multiple license file found throughout the repo, might want to change this to be a single one in the 
  root of the repo
- Probably more things that could be done to improve the repo but I'm done for now...

gl have fun :)

**Comment by riek-lt** [comment]
- Fun textswapper is deleted
- textswapfiles is not. 
- There's 1 readme.md for the root, and 1 readme.txt for a zip I'm sending to others.
- Created a `license` file
- I didn't feel the need to add an `index.html`, but I've renamed audio.html to make more sense
- Yes 🙈
- Done
- Probably
